version: '2'
networks:
  hackrva:
    driver: bridge
volumes:
  certstore:
services:
  gateway:
    build: ./gateway
    ports:
      - 80:80
      - 443:43
    networks:
      hackrva:
        aliases:
          - gateway
    volumes:
      - ./gateway/sites:/usr/local/apache2/conf/sites
      - certstore:/etc/letsencrypt/live
  database:
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      hackrva:
        aliases:
          - database
    volumes:
      - ../mysql:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
  games:
    build: ./games
    networks:
      hackrva:
        aliases:
          - games
  wiki:
    build: ./wiki
    depends_on:
      - database
    networks:
      hackrva:
        aliases:
          - wiki
    volumes:
      - ../mediawiki_images:/var/www/html/mediawiki_images
#   chat:
#     build: ./chat
#     networks:
#       hackrva:
#         aliases:
#           - chat
